package model;

/**
 * this class represents a safety alert generated by the system
 * 
 * an alert contains the type of issue that is found along with the
 * severity level and readable message that be displayed in the frontend
 */
public class Alert {

    private String alertType;
    private String severity;
    private String message;

    public Alert() {
    }

    public Alert(String alertType, String severity, String message) {
        this.alertType = alertType;
        this.severity = severity;
        this.message = message;
    }

    /**
     * getting the alert type
     * @return returns the type of alert
     */
    public String getAlertType() {
        return this.alertType;
    }

    /**
     * getting the severity of the alert
     * @return returns the alert severity
     */
    public String getSeverity() {
        return this.severity;
    }

    /**
     * getting the message of the alert
     * @return returns the alert message
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * setting the alert type
     * @param alertType the type of alert
     */
    public void setAlertType(String alertType) {
        this.alertType = alertType;
    }

    /**
     * setting the severity of the alert
     * @param severity the severity
     */
    public void setSeverity(String severity) {
        this.severity = severity;
    }

    /**
     * setting the message for the alert
     * @param message the alert message
     */
    public void setMessage(String message) {
        this.message = message;
    }

    @Override
    public String toString() {
        return "Alert{" +
                "alertType='" + alertType + '\'' +
                ", severity='" + severity + '\'' +
                ", message='" + message + '\'' +
                '}';
    }
}